// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYc7xXvk8gxZanQ-FJbtqscDJ5x8ZF0k',
    appId: '1:140254491068:web:adb20969d515cbc9c2bbb9',
    messagingSenderId: '140254491068',
    projectId: 'footsal-51dea',
    authDomain: 'footsal-51dea.firebaseapp.com',
    storageBucket: 'footsal-51dea.firebasestorage.app',
    measurementId: 'G-F56QTW353G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4Qum9ZSSgvsfNYqGaJiFH1dG74riOSE',
    appId: '1:140254491068:android:71fd4cfdf5f9ac53c2bbb9',
    messagingSenderId: '140254491068',
    projectId: 'footsal-51dea',
    storageBucket: 'footsal-51dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZU8x_O6GInu3MGgIvsOc5YHVrMC04tkk',
    appId: '1:140254491068:ios:ef8bc1f7f82c4fffc2bbb9',
    messagingSenderId: '140254491068',
    projectId: 'footsal-51dea',
    storageBucket: 'footsal-51dea.firebasestorage.app',
    iosBundleId: 'com.seokho.projk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZU8x_O6GInu3MGgIvsOc5YHVrMC04tkk',
    appId: '1:140254491068:ios:ef8bc1f7f82c4fffc2bbb9',
    messagingSenderId: '140254491068',
    projectId: 'footsal-51dea',
    storageBucket: 'footsal-51dea.firebasestorage.app',
    iosBundleId: 'com.seokho.projk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsYc7xXvk8gxZanQ-FJbtqscDJ5x8ZF0k',
    appId: '1:140254491068:web:15a89b39005e8819c2bbb9',
    messagingSenderId: '140254491068',
    projectId: 'footsal-51dea',
    authDomain: 'footsal-51dea.firebaseapp.com',
    storageBucket: 'footsal-51dea.firebasestorage.app',
    measurementId: 'G-6EY5S55N7Z',
  );
}
